[versions]

kotlin = "1.7.10"
kotlin-serialization = "1.4.0"

plagubot = "2.3.3"
kslog = "0.5.2"

gh-release = "2.4.1"

[libraries]

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

plagubot-plugin = { module = "dev.inmo:plagubot.plugin", version.ref = "plagubot" }
kslog = { module = "dev.inmo:kslog", version.ref = "kslog" }

# buildscript classpaths

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin" }
gh-release-plugin = { module = "com.github.breadmoirai:github-release", version.ref = "gh-release" }
